### ISSUE TITLE
route issue on the left menu

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-demo#118]
spa application is launched. Start page is displayed.

I click on quick search icon : left panel slides. I close the panel by clicking on the cross.
I click on home menu : the quick search panel is displayed.

I reproduced this behaviour every time.

**Comment by Bernardstanislas** [comment]
see https://github.com/KleeGroup/focus-demo/commit/0c25e559eb4e8c032f85adaf64c29f5c6b5195df
