### ISSUE TITLE
[search-bar] relaunch the search when press ENTER

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-demo#141]

**Comment by pierr** [comment]
OK, but it think this will hide another bug wich is when i come back to a page, the search is not relaunch until i type a new work in the search bar.
I agree the enter keypress, should trigger the search, but let's not forget the other bug.

**Comment by Bernardstanislas** [comment]
see https://github.com/KleeGroup/focus-components/commit/5a9e0c234b28541deb41e1ff63e70ef8537a1254
