### ISSUE TITLE
[advanced-search] if the search is empty : get all results

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-demo#142]

**Comment by pierr** [comment]
There are two bugs:
- Vertigo: replace `''`with  `*`
- On the focus side, be sure to trigger the search even if the criteria is empty (maybe with  the enter click)

**Comment by Tommass** [comment]
focus bug is declared in an other issue.

**Comment by Bernardstanislas** [comment]
See https://github.com/KleeGroup/focus-demo/commit/05d6a24aab1eac5cad6bfd80b2aeec994c67d068
