### ISSUE TITLE
[back-to-top] Implement it

### ISSUE THREAD

**Issue by Bernardstanislas** [KleeGroup/focus-demo#50]

**Comment by pierr** [comment]
Add the button in the detal and the search

**Comment by pierr** [comment]
https://github.com/KleeGroup/focus-components/commit/094193f1388c907c3b5b77c20799a2031475c724

**Comment by pierr** [comment]
I think i will add it to the sticky navigation component with an activation props because it is the same scroll target.

**Comment by pierr** [comment]
I change my mind as this component will be use in the `advanced-search` page.

**Comment by pierr** [comment]
I just think the behaviour of the animation for scrolling to the page's top should be dependent on the distance from the top. Because the lower you are, the fastest it feels. Maybe we'll have to improve it with a  non linear transformation.

**Comment by pierr** [comment]
`z-index` should be lower than the `Popin` and superior to the `DeveloperBar` @tommass ?
