### ISSUE TITLE
[search] don't display scope with no results

### ISSUE THREAD

**Issue by Tommass** [KleeGroup/focus-demo#81]
if search don't return result for a scope, don't display le scope.

if there is no scope to display, show a message "No result" (in focus-components)

![image](https://cloud.githubusercontent.com/assets/5349745/8130390/15ce8c62-1112-11e5-94f8-e7b327337843.png)

**Comment by Bernardstanislas** [comment]
You mean display the scope, but with a 'no results' message under ?
